<?php

/*********************************************************************
* Extension configuration file for ext "svconnector_csv".
*
* Generated by ext 11-06-2015 08:19 UTC
*
* https://github.com/t3elmar/Ext
*********************************************************************/

$EM_CONF[$_EXTKEY] = array (
  'title' => 'Connector service - CSV',
  'description' => 'Connector service for reading a CSV or similar flat file',
  'category' => 'services',
  'author' => 'Francois Suter (Cobweb)',
  'author_email' => 'typo3@cobweb.ch',
  'state' => 'stable',
  'uploadfolder' => 0,
  'createDirs' => '',
  'clearCacheOnLoad' => 1,
  'author_company' => '',
  'version' => '1.5.2',
  'constraints' =>
  array (
    'depends' =>
    array(
      'typo3' => '6.2.0-7.99.99',
      'svconnector' => '2.4.0-0.0.0',
    ),
    'conflicts' =>
    array (
    ),
    'suggests' =>
    array (
    ),
  ),
  'comment' => 'Bug fix: now properly ignores empty lines in CSV files.',
  'user' => 'francois',
);

?>